import StyledComponentsRegistry from '@/lib/AntdRegistry';
import ReduxProvider from '@/lib/Redux/ReduxProvider';
import '@/styles/globals.css';
import theme from '@/styles/theme';
import { ConfigProvider } from 'antd';
import { Inter } from 'next/font/google';
import PropTypes from 'prop-types';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'PIAS AI-READ',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} relative`}>
        <StyledComponentsRegistry>
          <ReduxProvider>
            <ConfigProvider theme={theme}>{children}</ConfigProvider>
          </ReduxProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node,
};
